apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: kjcme5cut-go 
  janus-idp.io/tekton: kjcme5cut-go
  backstage.io/kubernetes-id: kjcme5cut-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kjcme5cut-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  