apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: kjcme5cut-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kjcme5cut-go 
  name: kjcme5cut-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: kjcme5cut-go 
